services:
  postgres:
    image: postgres:15-alpine
    container_name: securecenter_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: securecenter_v1
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d securecenter_v1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - securecenter_network

  dotnet_db:
    image: postgres:16-alpine
    container_name: securecenter_dotnet_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: securecenter_dotnet
      POSTGRES_USER: ${DOTNET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOTNET_POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dotnet_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - securecenter_network

volumes:
  postgres_data:
    name: securecenter_postgres_data
  dotnet_postgres_data:
    name: securecenter_dotnet_postgres_data

networks:
  securecenter_network:
    name: securecenter_network
