export enum SystemType {
    WEB_APPLICATION = "WEB_APPLICATION",
    NETWORK_SYSTEM = "NETWORK_SYSTEM",
    DATABASE_SYSTEM = "DATABASE_SYSTEM",
    CLOUD_SERVICE = "CLOUD_SERVICE",
    LEGACY_SYSTEM = "LEGACY_SYSTEM",
    OTHER = "OTHER"
}
export enum SystemCriticality {
    HIGH = "HIGH",
    MODERATE = "MODERATE",
    LOW = "LOW"
}
export enum SystemStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    DECOMMISSIONED = "DECOMMISSIONED",
    UNDER_DEVELOPMENT = "UNDER_DEVELOPMENT"
}
